#!/usr/bin/env bash
# Scan handlers/ and generate handlers/_registry.ts with explicit imports.
# This file is git-ignored; regenerated on every build/test/validate.
# Required because Bun does not support import.meta.glob (Vite-only feature).

set -euo pipefail

cd "$(dirname "$0")/../.."

OUTPUT="handlers/_registry.ts"

{
  echo "// AUTO-GENERATED by scripts/ci/codegen-handlers.sh — DO NOT EDIT BY HAND"
  echo "// Regenerated on every build/test/validate. Git-ignored."
  echo "// To add a tool: drop a file in handlers/<name>.ts; the next CI run picks it up."
  echo ""
  echo "import type { HandlerDef } from '../types';"
  echo ""

  # Imports — sorted for stable output. Skip files starting with _ (e.g. _registry.ts).
  for file in $(find handlers -maxdepth 1 -name '*.ts' -not -name '_*' | sort); do
    name="$(basename "$file" .ts)"
    echo "import ${name}Handler from './${name}';"
  done

  echo ""
  echo "export const handlers: HandlerDef[] = ["

  for file in $(find handlers -maxdepth 1 -name '*.ts' -not -name '_*' | sort); do
    name="$(basename "$file" .ts)"
    echo "  ${name}Handler,"
  done

  echo "];"
} > "$OUTPUT"

count=$(grep -c '^import .*Handler from' "$OUTPUT" || echo 0)
echo "codegen: wrote $OUTPUT with $count handlers"
